### ISSUE TITLE
Does jira-connector allow to include a certificate when making a request to jira?

### ISSUE THREAD

**Issue by Ady9N** [floralvikings/jira-connector#132]
Recently our Jira team introduced a new cert.pem (and now I could not connect to jira anymore.
The Error is:
jira search returns error: { Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }

Using node server.

here is the connection to jira based on basic authentication:
var jira = new jiraClient({
    host: 'jira-host.com',
    port: '8443',
    basic_auth: {
        base64: base64Str
    },
}); 

Is even possible to pass the certificate in the jira-connector?

Thanks,
Ady

**Comment by MrRefactoring** [comment]
Hey. How do I understand it is that you can no longer connect using basic auth?

Since December 1, 2018 Atlassian have marked basic auth as an outdated version of authorization and removed the possibility of its use.

You can read about it [here](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/)

Now the only possible authentication method is [OAuth2.0](https://developer.atlassian.com/cloud/jira/platform/oauth-2-authorization-code-grants-3lo-for-apps/)

**Comment by MrRefactoring** [comment]
If your question was to use the proxy in this library, then the answer is no, at the moment there is no such functionality here. I will include this issue in my [library](https://github.com/MrRefactoring/jira-api-wrapper)

**Comment by MrRefactoring** [comment]
Please test the following [solution](https://github.com/MrRefactoring/jira-api-wrapper/issues/20#issuecomment-463518272) to your problem.

**Comment by MrRefactoring** [comment]
Solved in 2.12.0 version
